language: ruby
rvm:
- 2.3.0
deploy:
  provider: heroku
  api_key:
    secure: dLrw7lgmf3sLIb77v24EHSw+QM1UiXxo6UcTnDOpGoFFW9KDPkRhLb3/VtApnSvSa3m5Uzi5VsOdaLmoVnJFFk9XlryTddqGUiGqll75VnNPVs4SiMk2UGRVdjducODhakhZvkP8fbWF+9GsANJ6JnSSGtL/OvnXD0sC/Lyi6TnNwXDyY0gbr9RxqeN9FODQPRzi6pChxYBEpqz0Xbd0mpgIIBQLzOAFMl+RFEG6gsE0AvDBTXyNq7pc1EWzhnF8+ZB1UMYxTv25APhwIGiQtADNnKxbr7aZZvJ1nXbJj2/xGd0FWGrqdp6RRuCNA4GrYYRtmjbGjFNLM8X7A2rv4EugUjkFK4kVfGz+ZQMt8UsmR3wgT3VXq6wIXKvBkMQS3YkNk0S7zU4pdO0CgPlVUkN/RFB0imQJcJdOfe8ZPq4BG3h3Ie/A7zHBS95eTZ+j2HmsdqGAsaps+5vzcwNBhSQPX+JhL6UcJXdMStaQdmLurVAhzdCgplTNc1wNGlf5P3AT+2qnqWxahJxEPdboOJ585OyaP4F5NUZEzWb+LL0p9g3iJ5LEYrYns3pheKZjmEAxIkyt/CWx3MYZijCoTcXH+VDyYbgFOa6gq0wJky4G8Wn4/tH2X6LauBXFHE5CGLAOr2Z0cyFsOpro121Pk+FOH0qnLjTSwZPDVj5lJ2g=
  app: projet
  on:
    repo: lisamaison/projet
